/**
 * SAP MM (Materials Management) Reference Data
 * Tables, Transactions, Fiori Apps, CDS Views, BAPIs, and Integration Points
 */

export const MM_TABLES = {
  procurement: {
    EKKO: "Purchase Order Header",
    EKPO: "Purchase Order Item",
    EKBE: "Purchase Order History",
    EBAN: "Purchase Requisition",
    EBKN: "Purchase Requisition Account Assignment",
    EINA: "Purchasing Info Record – General",
    EINE: "Purchasing Info Record – Purchasing Org",
    EKET: "Scheduling Agreement Schedule Lines",
    EKAB: "Release Documentation (PO)",
    LFA1: "Vendor Master – General",
    LFB1: "Vendor Master – Company Code",
    LFM1: "Vendor Master – Purchasing Org",
  },
  inventory: {
    MARD: "Storage Location Data for Material",
    MARC: "Plant Data for Material",
    MARA: "General Material Data",
    MAKT: "Material Descriptions",
    MBEW: "Material Valuation",
    MKPF: "Material Document Header",
    MSEG: "Material Document Segment",
    MCHB: "Batch Stocks",
    MSLB: "Special Stocks – Vendor",
    MSKU: "Special Stocks – Sales Order",
    RESB: "Reservation Document",
  },
  invoiceVerification: {
    RBKP: "Invoice Document Header",
    RSEG: "Invoice Document Item",
    BSEG: "Accounting Document Segment",
    BKPF: "Accounting Document Header",
    REGUH: "Settlement Data – Payment",
    REGUP: "Processed Items – Payment",
  },
  masterData: {
    MARA: "Material Master – General",
    MARC: "Material Master – Plant",
    MARD: "Material Master – Storage Location",
    MBEW: "Material Master – Valuation",
    MVKE: "Material Master – Sales",
    T001W: "Plant Master",
    T001L: "Storage Location Master",
    T024: "Purchasing Groups",
    T161: "Purchasing Document Types",
    T163: "Item Categories in Purchasing",
  },
};

export const MM_TCODES = {
  purchaseRequisition: {
    ME51N: "Create Purchase Requisition",
    ME52N: "Change Purchase Requisition",
    ME53N: "Display Purchase Requisition",
    ME5A: "List Display of Purchase Requisitions",
    ME5J: "Delete Purchase Requisition",
  },
  purchaseOrder: {
    ME21N: "Create Purchase Order",
    ME22N: "Change Purchase Order",
    ME23N: "Display Purchase Order",
    ME2M: "PO by Material",
    ME2N: "PO by PO Number",
    ME2L: "PO by Vendor",
    ME28: "Release Purchase Order",
    ME29N: "Release Strategy – PO",
    ME9F: "Output – PO",
  },
  contracts: {
    ME31K: "Create Contract",
    ME32K: "Change Contract",
    ME33K: "Display Contract",
    ME31L: "Create Scheduling Agreement",
    ME32L: "Change Scheduling Agreement",
    ME33L: "Display Scheduling Agreement",
    ME35: "Release Outline Agreement",
  },
  goodsMovement: {
    MIGO: "Goods Movement (All Types)",
    MB01: "Goods Receipt for PO",
    MB1A: "Goods Issue",
    MB1B: "Transfer Posting",
    MB1C: "Other Goods Receipts",
    MB31: "GR for Production Order",
    MB51: "Material Document List",
    MB52: "Warehouse Stocks on Hand",
    MMBE: "Stock Overview",
    MB5B: "Stocks on Posting Date",
  },
  invoiceVerification: {
    MIRO: "Enter Incoming Invoice",
    MIR4: "Display Invoice Document",
    MIR5: "Display Invoice Document List",
    MIR6: "Invoice Overview",
    MIR7: "Park Incoming Invoice",
    MRBR: "Release Blocked Invoices",
  },
  inventoryManagement: {
    MI01: "Create Physical Inventory Document",
    MI04: "Enter Inventory Count",
    MI07: "Post Inventory Differences",
    MI20: "Print Physical Inventory Document List",
    MI31: "Batch Input – Create Phys. Inv. Doc",
    MIDO: "Physical Inventory Overview",
  },
  masterData: {
    MM01: "Create Material Master",
    MM02: "Change Material Master",
    MM03: "Display Material Master",
    MK01: "Create Vendor (Purchasing)",
    MK02: "Change Vendor (Purchasing)",
    ME11: "Create Purchasing Info Record",
    ME12: "Change Purchasing Info Record",
    ME01: "Maintain Source List",
  },
  reporting: {
    ME80FN: "Purchasing Reporting",
    MB5L: "List of Stock Values: Balance Sheet",
    "MC.9": "Inventory Analysis – Plant",
    MC44: "Inventory Turnover Analysis",
    ME2M: "Purchase Orders by Material",
    S_ALR_87012090: "Vendor Evaluation",
  },
  config: {
    SPRO: "IMG – Customizing",
    OLME: "MM Customizing",
    OME2: "Define Number Ranges for PO",
    OMEC: "Define Purchasing Document Types",
  },
};

export const MM_FIORI_APPS = {
  procurement: {
    F0842: "Manage Purchase Requisitions",
    F2229: "Create Purchase Requisition – Advanced",
    F0843: "Manage Purchase Orders",
    F2666: "Create Purchase Order – Advanced",
    F1644: "Approve Purchase Orders",
    F1645: "Approve Purchase Requisitions",
    F2680: "Manage Purchase Contracts",
    F2681: "Create Purchase Contract",
    F3814: "Manage Supplier Invoices",
  },
  inventory: {
    F3093: "Manage Stock",
    F2755: "Post Goods Receipt for Purchase Order",
    F2823: "Post Goods Issue",
    F2412: "Manage Physical Inventory Documents",
    F3170: "Count Physical Inventory",
    F3693: "Manage Stock Transfer",
  },
  analytics: {
    F0844: "Monitor Purchase Order Items",
    F1243: "Purchase Order Overview",
    F1702: "Stock – Single Material",
    F2637: "Stock – Multiple Materials",
    F0325: "Procurement Overview Page",
  },
};

export const MM_CDS_VIEWS = {
  procurement: {
    I_PURCHASEORDERAPI01: "Purchase Order API",
    I_PURCHASEREQUISITIONITEMAPI01: "Purchase Requisition Item API",
    I_PURCHASINGDOCUMENTHISTORY: "Purchasing Document History",
    I_PURCHASINGINFORECORD: "Purchasing Info Record",
    I_PURCHASECONTRACTITEMAPI01: "Purchase Contract Item API",
    C_PURCHASEORDERITEMQUERY: "PO Item Analytics",
    C_MMPUR_PURCHASEORDERITEM: "Purchase Order Item Consumption",
  },
  inventory: {
    I_MATERIALDOCUMENTITEMAPI01: "Material Document Item API",
    I_MATERIALSTOCK: "Material Stock",
    I_MATERIALSTOCKBYWAREHOUSE: "Stock by Warehouse",
    I_PHYSICALINVENTORYDOCITEMAPI01: "Physical Inventory Item API",
    C_MATERIALSTOCKANALYSIS: "Stock Analytics",
  },
  masterData: {
    I_PRODUCT: "Product Master",
    I_PRODUCTPLANT: "Product Plant Data",
    I_SUPPLIER: "Supplier Master",
    I_PURCHASINGORGANIZATION: "Purchasing Organization",
    I_PLANT: "Plant",
    I_STORAGELOCATION: "Storage Location",
  },
};

export const MM_BAPIS = {
  purchaseOrder: {
    BAPI_PO_CREATE1: "Create Purchase Order",
    BAPI_PO_CHANGE: "Change Purchase Order",
    BAPI_PO_GETDETAIL1: "Get PO Details",
    BAPI_PO_RELEASE: "Release Purchase Order",
  },
  purchaseRequisition: {
    BAPI_PR_CREATE: "Create Purchase Requisition",
    BAPI_PR_CHANGE: "Change Purchase Requisition",
    BAPI_PR_GETDETAIL: "Get PR Details",
  },
  goodsMovement: {
    BAPI_GOODSMVT_CREATE: "Create Goods Movement",
    BAPI_GOODSMVT_GETDETAIL: "Get Goods Movement Details",
  },
  materialMaster: {
    BAPI_MATERIAL_SAVEDATA: "Create/Change Material Master",
    BAPI_MATERIAL_GET_DETAIL: "Get Material Details",
  },
  vendor: {
    BAPI_VENDOR_CREATE: "Create Vendor",
    BAPI_VENDOR_GETDETAIL: "Get Vendor Details",
  },
};

export const MM_MOVEMENT_TYPES = {
  "101": "GR for Purchase Order",
  "102": "GR for PO – Reversal",
  "103": "GR into Blocked Stock",
  "105": "Release from Blocked Stock",
  "122": "Return to Vendor",
  "161": "GR for Production Order",
  "201": "GI for Cost Center",
  "261": "GI for Production Order",
  "301": "Transfer Posting – Plant to Plant",
  "311": "Transfer Posting – SLoc to SLoc",
  "501": "GR without PO",
  "551": "Scrapping",
  "561": "Initial Entry of Stock Balances",
  "601": "GI for Delivery (SD)",
};

export const MM_INTEGRATION_POINTS = {
  FI: {
    description: "Financial Accounting Integration",
    touchpoints: [
      "Goods Receipt → Accounting Document (GR/IR clearing)",
      "Invoice Verification → FI Document posting",
      "Material Valuation → General Ledger updates",
      "Vendor Master → Shared with AP (Accounts Payable)",
      "Automatic account determination via movement types",
      "Accruals/deferrals for PO commitments",
    ],
    tables: ["BSEG", "BKPF", "SKA1", "T030"],
  },
  CO: {
    description: "Controlling Integration",
    touchpoints: [
      "Purchase Requisition → Cost Center / WBS assignment",
      "Purchase Order → Account Assignment categories (K, F, P, etc.)",
      "Goods Issue → Cost Center / Order consumption",
      "Overhead cost allocation",
      "Activity-based costing for procurement activities",
    ],
    tables: ["COBK", "COEP", "COSS", "COSP"],
  },
  SD: {
    description: "Sales & Distribution Integration",
    touchpoints: [
      "Third-party procurement (PO created from Sales Order)",
      "Stock transfer orders between plants",
      "Material availability check (ATP)",
      "Intercompany procurement scenarios",
    ],
    tables: ["VBAK", "VBAP", "LIPS", "VBRK"],
  },
  PP: {
    description: "Production Planning Integration",
    touchpoints: [
      "MRP → Automatic PR creation",
      "Production Order → Goods Issue (backflush)",
      "BOM explosion → Material requirements",
      "Planned orders → Purchase requisitions conversion",
      "Subcontracting scenarios",
    ],
    tables: ["PLAF", "AFKO", "AFPO", "RESB", "STPO"],
  },
  QM: {
    description: "Quality Management Integration",
    touchpoints: [
      "GR with quality inspection (stock posted to QI stock)",
      "Usage decision → Release or reject stock",
      "Vendor evaluation based on quality scores",
      "Source inspection before GR",
      "Certificate management",
    ],
    tables: ["QALS", "QAVE", "QASE", "QAMV"],
  },
  WM_EWM: {
    description: "Warehouse / Extended Warehouse Mgmt Integration",
    touchpoints: [
      "GR triggers put-away in WM/EWM",
      "GI triggers pick from WM/EWM",
      "Transfer requirements and transfer orders",
      "Bin management and storage type determination",
      "Decentralized EWM with RFC/AIF integration",
    ],
    tables: ["LQUA", "LTAP", "LAGP", "/SCWM/AQUA"],
  },
  SRM_ARIBA: {
    description: "Procurement Cloud Integration (Ariba/SRM)",
    touchpoints: [
      "Requisition replication to Ariba",
      "PO creation via Ariba guided buying",
      "Supplier management sync",
      "Contract replication",
      "Invoice processing in Ariba",
    ],
    tables: [],
  },
};

export const MM_PROCESS_AREAS = [
  "Procure-to-Pay (P2P)",
  "Source-to-Pay (S2P)",
  "Inventory Management",
  "Invoice Verification (MIRO/LIV)",
  "Material Requirements Planning (MRP)",
  "Vendor Evaluation",
  "Purchasing Info Records & Source Lists",
  "Outline Agreements (Contracts & Scheduling Agreements)",
  "Subcontracting",
  "Consignment Processing",
  "Pipeline Processing",
  "Third-Party Processing",
  "Stock Transfers (Intra- and Inter-company)",
  "Physical Inventory",
  "Batch Management",
  "Serial Number Management",
  "Release Strategy (PR and PO)",
  "Automatic Account Determination",
  "GR/IR Clearing",
  "Material Valuation (Standard / Moving Average)",
];

export const MM_CONFIG_AREAS = [
  "Purchasing Organization structure",
  "Document types (PR, PO, Contract, SA)",
  "Number ranges for purchasing documents",
  "Item categories",
  "Account assignment categories",
  "Release strategies (PR / PO)",
  "Movement types and automatic account determination",
  "Valuation classes and valuation areas",
  "MRP configuration (MRP types, lot sizes, planning strategies)",
  "Tolerance limits (price, quantity, invoice)",
  "Output determination (PO forms, messages)",
  "Vendor evaluation criteria and weights",
  "Source determination and quota arrangement",
  "Batch management activation and configuration",
  "Split valuation configuration",
];
