/**
 * SAP SD (Sales & Distribution) Reference Data
 * Tables, Transactions, Fiori Apps, CDS Views, BAPIs, and Integration Points
 */

export const SD_TABLES = {
  salesDocuments: {
    VBAK: "Sales Document Header",
    VBAP: "Sales Document Item",
    VBEP: "Sales Document Schedule Line",
    VBKD: "Sales Document Business Data",
    VBUK: "Sales Document Header Status",
    VBUP: "Sales Document Item Status",
    VBPA: "Sales Document Partner",
    VBFA: "Sales Document Flow",
    VBBE: "Sales Requirements: Individual Records",
    VBBS: "Sales Requirements: Totals Records",
  },
  delivery: {
    LIKP: "Delivery Document Header",
    LIPS: "Delivery Document Item",
    VTTP: "Shipment Item (Shipment/Delivery Assignment)",
    VTTS: "Shipment Stage",
    VTPA: "Shipment Partner",
    VTTK: "Shipment Header",
    VEPO: "Packing: Item to Handling Unit Assignment",
    VEKP: "Handling Unit Header",
    VLPMA: "Delivery Due List: Selection Criteria",
  },
  billing: {
    VBRK: "Billing Document Header",
    VBRP: "Billing Document Item",
    VBRL: "Billing Document Log (SD Billing Log)",
    VBREVE: "Rebate Index (Billing Items)",
    BSAD: "Accounting: Secondary Index for Customers (Cleared Items)",
    BSID: "Accounting: Secondary Index for Customers (Open Items)",
  },
  pricing: {
    KONV: "Conditions in Sales Document (Document Conditions)",
    KONP: "Condition Item (Condition Record)",
    KONH: "Condition Header (Condition Record)",
    A004: "Condition Table: Material with Release Status",
    A005: "Condition Table: Customer/Material",
    A006: "Condition Table: Price List Type/Currency/Material",
    A304: "Condition Table: Freight – Material/Ship-To",
    A305: "Condition Table: Freight – Departure/Destination Zone",
    T685: "Condition Types: Definition",
    T683: "Pricing Procedures: Definition",
  },
  masterData: {
    KNA1: "Customer Master – General Data",
    KNB1: "Customer Master – Company Code Data",
    KNVV: "Customer Master – Sales Area Data",
    KNVP: "Customer Master – Partner Functions",
    KNVH: "Customer Hierarchy",
    MVKE: "Material Master – Sales Data (Sales Org/Distribution Channel)",
    TVAK: "Sales Document Types",
    TVAP: "Sales Document Item Categories",
    TVLV: "Shipping Point Determination",
    TVRO: "Route Determination",
    TVSTZ: "Schedule Line Categories",
  },
};

export const SD_TCODES = {
  salesOrder: {
    VA01: "Create Sales Order",
    VA02: "Change Sales Order",
    VA03: "Display Sales Order",
    VA05: "List of Sales Orders",
    VA21: "Create Quotation",
    VA22: "Change Quotation",
    VA23: "Display Quotation",
    VA41: "Create Contract",
    VA42: "Change Contract",
    VA43: "Display Contract",
    VA11: "Create Inquiry",
    VA12: "Change Inquiry",
    VA13: "Display Inquiry",
  },
  delivery: {
    VL01N: "Create Outbound Delivery with Order Reference",
    VL02N: "Change Outbound Delivery",
    VL03N: "Display Outbound Delivery",
    VL06O: "Outbound Delivery Monitor",
    VL06I: "Inbound Delivery Monitor",
    VL10A: "Delivery Due List by Shipping Point (Sales Orders)",
    VL10B: "Delivery Due List by Purchase Orders",
    VL10C: "Delivery Due List by Shipping Point (Purchase Orders)",
    VT01N: "Create Shipment",
    VT02N: "Change Shipment",
  },
  billing: {
    VF01: "Create Billing Document",
    VF02: "Change Billing Document",
    VF03: "Display Billing Document",
    VF04: "Billing Due List (Collective Billing)",
    VF11: "Cancel Billing Document",
    VF21: "Create Invoice List",
    VF26: "Cancel Invoice List",
    VF44: "Maintain Rebate Agreements",
    VF45: "Rebate Settlement",
    VFX3: "Release Billing Documents for Accounting",
  },
  pricing: {
    VK11: "Create Condition Record",
    VK12: "Change Condition Record",
    VK13: "Display Condition Record",
    VK31: "Create Condition Records (Mass Maintenance)",
    VK32: "Change Condition Records (Mass Maintenance)",
    VK14: "Create Condition with Reference",
    "V/06": "Pricing Report",
    "V/08": "Pricing Procedure Determination",
  },
  creditManagement: {
    FD32: "Change Customer Credit Management",
    FD33: "Display Customer Credit Management",
    UKM_MP: "SAP Credit Management Master Data",
    "F.28": "Customer Credit Management – Mass Change",
    S_ALR_87012218: "Credit Overview for Customers",
  },
  outputDetermination: {
    VV31: "Create Output Condition Records (Sales)",
    VV32: "Change Output Condition Records (Sales)",
    VV33: "Display Output Condition Records (Sales)",
    NACE: "Output Control – Condition Maintenance",
    VV21: "Create Output Condition Records (Shipping)",
    VV22: "Change Output Condition Records (Shipping)",
    VV61: "Create Output Condition Records (Billing)",
    VV62: "Change Output Condition Records (Billing)",
  },
  masterData: {
    XD01: "Create Customer (Centrally)",
    XD02: "Change Customer (Centrally)",
    XD03: "Display Customer (Centrally)",
    VD01: "Create Customer (Sales)",
    VD02: "Change Customer (Sales)",
    VD03: "Display Customer (Sales)",
    BP: "Business Partner (S/4HANA)",
    VD51: "Create Customer-Material Info Record",
    VD52: "Change Customer-Material Info Record",
    VD53: "Display Customer-Material Info Record",
    MMR1: "Create Raw Material",
  },
  reporting: {
    VA05: "List of Sales Orders",
    VL06: "Delivery Monitor (All Deliveries)",
    VF05: "List of Billing Documents",
    "MC+": "Sales Analysis (SIS – Standard Analyses)",
    S_ALR_87012186: "Customer Analysis – List of Sales Orders",
    S_ALR_87012197: "Billing Document Analysis",
    "VB(8": "List of Rebate Agreements",
    VA15: "Inquiries List",
    VA25: "Quotations List",
    VA45: "List of Contracts",
  },
  config: {
    SPRO: "IMG – Customizing",
    OVZG: "Define Delivery Item Categories",
    VOV8: "Define Sales Document Types",
    VOV7: "Define Item Categories",
    VOV6: "Define Schedule Line Categories",
    OVLK: "Define Billing Types",
    OVK1: "Pricing Procedure Determination",
    VTLA: "Copy Control: Delivery to Billing",
    VTAA: "Copy Control: Sales Document to Sales Document",
    VTFL: "Copy Control: Delivery to Billing Document",
    VTFA: "Copy Control: Sales Document to Billing Document",
  },
};

export const SD_FIORI_APPS = {
  salesOrder: {
    F0842A: "Manage Sales Orders",
    F1705: "Create Sales Orders (V2)",
    F2501: "Track Sales Orders",
    F6587: "Manage Sales Orders (V2)",
    F1706: "Manage Quotations",
    F2191: "Create Quotation",
    F3893: "Manage Sales Contracts",
    F1713: "Create Sales Contract",
    F3815: "Manage Inquiries",
    F2367: "Approve Sales Orders",
  },
  delivery: {
    F1709: "Create Outbound Deliveries",
    F2079: "Manage Outbound Deliveries",
    F2080: "Pick Outbound Deliveries",
    F2498: "Post Goods Issue for Outbound Deliveries",
    F3816: "Manage Inbound Deliveries",
    F1735: "Create Shipment",
  },
  billing: {
    F2581: "Create Billing Documents",
    F2071: "Manage Billing Documents",
    F2880: "Manage Billing Document Requests",
    F5048: "Create Credit Memo Request",
    F5049: "Create Debit Memo Request",
  },
  analytics: {
    F0812: "Sales Order Fulfillment",
    F1564: "Sales Performance – Overview",
    F1282: "Monitor Sales Orders",
    F2635: "Billing Document Overview",
    F2636: "Delivery Overview",
    F3297: "Overdue Sales Orders",
    F2889: "Incomplete Sales Orders",
    F1283: "Sales Order Fulfillment Issues",
  },
};

export const SD_CDS_VIEWS = {
  salesOrder: {
    I_SalesOrderAPI01: "Sales Order API (Header)",
    I_SalesOrderItemAPI01: "Sales Order Item API",
    I_SalesOrderScheduleLineAPI01: "Sales Order Schedule Line API",
    I_SalesOrderPartnerAPI01: "Sales Order Partner API",
    I_SalesOrderPricingElementAPI01: "Sales Order Pricing Element API",
    C_SalesOrderItemQuery: "Sales Order Item Analytical Query",
    C_SalesDocumentItemDEX: "Sales Document Item Data Extraction",
    I_SalesQuotationAPI01: "Sales Quotation API",
    I_SalesContractAPI01: "Sales Contract API",
  },
  delivery: {
    I_DeliveryDocumentAPI01: "Delivery Document API (Header)",
    I_DeliveryDocumentItemAPI01: "Delivery Document Item API",
    I_ShipmentAPI01: "Shipment API",
    C_OutbDeliveryItemFs: "Outbound Delivery Item – Fact Sheet",
    C_DeliveryItemQuery: "Delivery Item Analytical Query",
  },
  billing: {
    I_BillingDocumentAPI01: "Billing Document API (Header)",
    I_BillingDocumentItemAPI01: "Billing Document Item API",
    I_BillingDocumentItemPrcgElmntAPI01: "Billing Document Pricing Element API",
    C_BillingDocumentItemQuery: "Billing Document Item Analytical Query",
  },
  masterData: {
    I_Customer: "Customer Master (Business Partner – Customer Role)",
    I_CustomerSalesArea: "Customer Sales Area Data",
    I_CustomerCompany: "Customer Company Code Data",
    I_ProductSalesDelivery: "Product Sales and Delivery Data",
    I_CustSalesPartnerFunc: "Customer Partner Function",
    I_CustomerMaterial: "Customer-Material Info Record",
  },
};

export const SD_BAPIS = {
  salesOrder: {
    BAPI_SALESORDER_CREATEFROMDAT2: "Create Sales Order",
    BAPI_SALESORDER_CHANGE: "Change Sales Order",
    BAPI_SALESORDER_GETLIST: "Get List of Sales Orders",
    BAPI_SALESORDER_GETSTATUS: "Get Sales Order Status",
    BAPI_SALESORDER_SIMULATE: "Simulate Sales Order",
    BAPI_QUOTATION_CREATEFROMDATA2: "Create Quotation",
    BAPI_CUSTOMERQUOTATION_CHANGE: "Change Quotation",
  },
  delivery: {
    BAPI_OUTB_DELIVERY_CREATE_SLS: "Create Outbound Delivery for Sales Order",
    BAPI_OUTB_DELIVERY_CHANGE: "Change Outbound Delivery",
    BAPI_OUTB_DELIVERY_CONFIRM_DEC: "Post Goods Issue for Outbound Delivery",
    BAPI_INB_DELIVERY_SAPMM_GR: "Post Goods Receipt for Inbound Delivery",
    BAPI_DELIVERYPROCESSING_EXEC: "Execute Delivery Processing",
  },
  billing: {
    BAPI_BILLINGDOC_CREATEMULTIPLE: "Create Billing Documents (Collective)",
    BAPI_BILLINGDOC_CREATE1: "Create Single Billing Document",
    BAPI_BILLINGDOC_CANCEL: "Cancel Billing Document",
    BAPI_BILLINGDOC_GETLIST: "Get List of Billing Documents",
  },
  customer: {
    BAPI_CUSTOMER_GETLIST: "Get List of Customers",
    BAPI_CUSTOMER_GETDETAIL2: "Get Customer Details",
    BAPI_CUSTOMER_CREATEFROMDATA1: "Create Customer Master",
    BAPI_CUSTOMER_CHANGEFROMDATA1: "Change Customer Master",
  },
};

export const SD_INTEGRATION_POINTS = {
  FI: {
    description: "Financial Accounting Integration",
    touchpoints: [
      "Billing Document → Accounting Document (Revenue posting)",
      "Revenue recognition and accruals via billing",
      "Credit management – customer credit limits and exposure",
      "Customer Master → Shared with AR (Accounts Receivable)",
      "Rebate accruals and settlement to FI",
      "Tax determination and posting in billing",
      "Cash discount and payment terms processing",
    ],
    tables: ["BKPF", "BSEG", "BSID", "BSAD", "KNKK"],
  },
  MM: {
    description: "Materials Management Integration",
    touchpoints: [
      "Third-party processing (Sales Order → Purchase Requisition → PO)",
      "Stock availability check / ATP (Available-to-Promise)",
      "Material determination and product substitution",
      "Intercompany stock transfer orders",
      "Goods issue from delivery reduces MM inventory",
      "Consignment fill-up and issue via SD",
    ],
    tables: ["EKKO", "EKPO", "MARD", "MARC", "RESB"],
  },
  PP: {
    description: "Production Planning Integration",
    touchpoints: [
      "Make-to-order (MTO) – Sales Order triggers production order",
      "Assembly processing / BOM explosion at order entry",
      "Availability check against planned and production orders",
      "Planning strategies (MTS, MTO, ATO) driven by SD requirements",
      "Individual and collective requirements from sales orders to MRP",
    ],
    tables: ["PLAF", "AFKO", "AFPO", "PBIM", "MDKP"],
  },
  EWM: {
    description: "Extended Warehouse Management Integration",
    touchpoints: [
      "Outbound delivery processing triggers pick/pack/ship in EWM",
      "Wave management and wave release for delivery processing",
      "Packing and handling unit management",
      "Yard management and dock appointment scheduling",
      "Proof of delivery (POD) confirmation flow back to SD",
    ],
    tables: ["/SCWM/AQUA", "/SCWM/ORDIM_O", "/SCWM/DLVH", "/SCWM/DLVI"],
  },
  TM: {
    description: "Transportation Management Integration",
    touchpoints: [
      "Transportation planning and optimization for deliveries",
      "Freight cost calculation and settlement",
      "Carrier selection and tendering",
      "Shipment creation and stage management",
      "Freight order creation from outbound deliveries",
      "Transportation charges posted to SD billing (freight billing)",
    ],
    tables: ["VTTK", "VTTS", "VTTP", "/SCMTMS/D_TORROT"],
  },
};

export const SD_PROCESS_AREAS = [
  "Order-to-Cash (O2C)",
  "Pricing & Conditions",
  "Shipping & Delivery",
  "Billing & Invoicing",
  "Credit Management",
  "Returns & Complaints (RMA Processing)",
  "Rebate Processing",
  "Intercompany Sales",
  "Third-Party Processing",
  "Consignment Sales",
  "Make-to-Order (MTO)",
  "Free-of-Charge Delivery",
  "Sales Contracts & Scheduling Agreements",
  "Quotation & Inquiry Management",
  "Availability Check (ATP)",
  "Output Determination (Forms, EDI, Email)",
  "Partner Determination",
  "Revenue Recognition",
];

export const SD_CONFIG_AREAS = [
  "Sales organization structure (Sales Org, Distribution Channel, Division)",
  "Document types (Order, Quotation, Contract, Returns, etc.)",
  "Item categories and item category determination",
  "Schedule line categories and schedule line determination",
  "Copy control rules (Order to Delivery, Delivery to Billing)",
  "Pricing procedures and pricing procedure determination",
  "Output determination (Condition-based output for orders, deliveries, billing)",
  "Partner determination procedures and partner types",
  "Text determination procedures",
  "Availability check rules (checking groups, checking rules)",
  "Credit management (credit control areas, risk categories, automatic checks)",
  "Shipping point determination (Shipping point, loading group, plant)",
  "Route determination (departure zone, transportation zone, shipping condition)",
  "Billing plan types (milestone billing, periodic billing)",
  "Incompletion procedures (header, item, partner, schedule line)",
  "Account determination (VKOA – Revenue account assignment)",
  "Free goods determination",
  "Material determination / product substitution",
  "Listing and exclusion",
];
