import { NextResponse } from "next/server";
import { isCalmConfigured, calmFetch } from "@/lib/services/calm-client";
import { prisma } from "@/lib/db";
import { logAudit } from "@/lib/audit";
import { safeErrorResponse } from "@/lib/api-error";
import { calmPushFsdSchema, validateBody } from "@/lib/validations";
import type { CalmDocument } from "@/lib/services/calm-types";

export async function POST(request: Request) {
  if (!isCalmConfigured()) {
    return NextResponse.json({ error: "SAP Cloud ALM is not configured" }, { status: 503 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const validated = validateBody(calmPushFsdSchema, body);
  if ("error" in validated) {
    return NextResponse.json({ error: validated.error }, { status: 400 });
  }

  const { fsdId, projectId, projectName } = validated.data;

  try {
    // Fetch the FSD from local database
    const fsd = await prisma.fsd.findUnique({ where: { id: fsdId } });
    if (!fsd) {
      return NextResponse.json({ error: "FSD not found" }, { status: 404 });
    }

    const documentName = `FSD: ${fsd.title}`;
    const documentContent = fsd.markdown;

    let calmDocId = fsd.calmDocumentId;

    if (calmDocId) {
      // Update existing document
      await calmFetch(
        `/api/calm-projects/v1/projects('${encodeURIComponent(projectId)}')/documents('${encodeURIComponent(calmDocId)}')`,
        {
          method: "PATCH",
          body: {
            name: documentName,
            content: documentContent,
            description: `Generated by SAP FSD Generator | Module: ${fsd.primaryModule} | Updated: ${new Date().toISOString()}`,
          },
        }
      );
    } else {
      // Create new document
      const result = await calmFetch<CalmDocument>(
        `/api/calm-projects/v1/projects('${encodeURIComponent(projectId)}')/documents`,
        {
          method: "POST",
          body: {
            name: documentName,
            content: documentContent,
            projectId,
            description: `Generated by SAP FSD Generator | Module: ${fsd.primaryModule} | Created: ${new Date().toISOString()}`,
          },
        }
      );
      calmDocId = result.id;
    }

    // Update local FSD with CALM linkage
    await prisma.fsd.update({
      where: { id: fsdId },
      data: {
        calmProjectId: projectId,
        calmProjectName: projectName,
        calmDocumentId: calmDocId,
      },
    });

    logAudit(
      "CALM_PUSH_FSD",
      "Fsd",
      fsdId,
      request,
      `Pushed to CALM project ${projectName} (doc: ${calmDocId})`
    );

    return NextResponse.json({
      success: true,
      calmDocumentId: calmDocId,
      message: fsd.calmDocumentId ? "FSD updated in CALM" : "FSD pushed to CALM",
    });
  } catch (error) {
    return NextResponse.json(
      { error: safeErrorResponse(error, "CALM push FSD") },
      { status: 500 }
    );
  }
}
